html/nsda/nsda/Controllers/EventmanageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nsda.Controllers
{
    public class EventmanageController : Controller
    {
        // GET: Eventmanage

        public ActionResult eventmanagelogin()
        {
            ViewBag.Message = "裁判登陆";
            return View();
        }
        public ActionResult eventmanageregform()
        {
            ViewBag.Message = "赛事管理员注册";
            return View();
        }
        public ActionResult eventmanage()
        {
            ViewBag.Message = "比赛进程管理";
            return View();
        }
        public ActionResult eventstart()
        {
            ViewBag.Message = "发起赛事";
            return View();
        }
        public ActionResult eventstartlists()
        {
            ViewBag.Message = "发起赛事";
            return View();
        }

        public ActionResult eventmanageplayer()
        {
            ViewBag.Message = "选手报名管理";
            return View();
        }
        public ActionResult eventmanageumpire()
        {
            ViewBag.Message = "裁判报名管理";
            return View();
        }
        public ActionResult manageumpire()
        {
            ViewBag.Message = "裁判管理";
            return View();
        }
        public ActionResult addjudge()
        {
            ViewBag.Message = "添加临时裁判";
            return View();
        }
        public ActionResult eventmanageroom()
        {
            ViewBag.Message = "Room管理";
            return View();
        }
        public ActionResult addroom()
        {
            ViewBag.Message = "添加Room";
            return View();
        }
        public ActionResult addassign()
        {
            ViewBag.Message = "添加指定";
            return View();
        }
        public ActionResult modifyroom()
        {
            ViewBag.Message = "修改Room";
            return View();
        }
        public ActionResult eventmanageknockout()
        {
            ViewBag.Message = "淘汰赛规则设置";
            return View();
        }
        public ActionResult eventmanageround()
        {
            ViewBag.Message = "循环赛规则设置";
            return View();
        }

        public ActionResult eventnewinfoconfirm()
        {
            ViewBag.Message = "开始执行对垒";
            return View();
        }
        public ActionResult eventopeninfocomfirm()
        {
            ViewBag.Message = "开始执行对垒";
            return View();
        }
        public ActionResult eventnewplayersignin()
        {
            ViewBag.Message = "新手组选手签到";
            return View();
        }
        public ActionResult eventopenplayersignin()
        {
            ViewBag.Message = "公开组选手签到";
            return View();
        }
        public ActionResult eventumpiresignin()
        {
            ViewBag.Message = "裁判签到管理";
            return View();
        }
        public ActionResult eventjudgesignin()
        {
            ViewBag.Message = "裁判签到";
            return View();
        }


        public ActionResult eventmanagecenter()
        {
            ViewBag.Message = "赛事管理员个人中心";
            return View();
        }
        public ActionResult addtmpplayer()
        {
            ViewBag.Message = "添加临时选手";
            return View();
        }

        public ActionResult doublecheck()
        {
            ViewBag.Message = "核对评分单";
            return View();
        }
        public ActionResult writegrades()
        {
            ViewBag.Message = "录入评分单";
            return View();
        }
        public ActionResult track()
        {
            ViewBag.Message = "查询";
            return View();
        }
        public ActionResult resulttrackaround()
        {
            ViewBag.Message = "循环赛赛果查询";
            return View();
        }
        public ActionResult resulttrackkonckout()
        {
            ViewBag.Message = "淘汰赛赛果查询";
            return View();
        }
        public ActionResult winnerlist()
        {
            ViewBag.Message = "获奖名单";
            return View();
        }
        public ActionResult prize()
        {
            ViewBag.Message = "奖项设置";
            return View();
        }
        public ActionResult addprize()
        {
            ViewBag.Message = "添加自定义奖项";
            return View();
        }
        public ActionResult octafinals()
        {
            ViewBag.Message = "Octafinals 评分单录入";
            return View();
        }
        public ActionResult againstaround()
        {
            ViewBag.Message = "执行对垒 循环赛";
            return View();
        }
        public ActionResult againstknockout()
        {
            ViewBag.Message = "执行对垒 淘汰赛";
            return View();
        }
        public ActionResult mapone()
        {
            ViewBag.Message = "对垒";
            return View();
        }
        public ActionResult maptwo()
        {
            ViewBag.Message = "对垒";
            return View();
        }
        public ActionResult mapfour()
        {
            ViewBag.Message = "对垒";
            return View();
        }
        public ActionResult mapeight()
        {
            ViewBag.Message = "对垒";
            return View();
        }
        public ActionResult mapsixteen()
        {
            ViewBag.Message = "对垒";
            return View();
        }
        public ActionResult mapthirtytwo()
        {
            ViewBag.Message = "对垒";
            return View();
        }
    }
}

html/nsda/nsda/Controllers/JudgeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nsda.Controllers
{
    public class JudgeController : Controller
    {
        // GET: Judge
        public ActionResult judgelogin()
        {
            ViewBag.Message = "裁判登陆";
            return View();
        }
        public ActionResult judgeregform()
        {
            ViewBag.Message = "裁判注册";
            return View();
        }
        public ActionResult judgecenter()
        {
            ViewBag.Message = "裁判管理";
            return View();
        }
        public ActionResult judgemessagebox()
        {
            ViewBag.Message = "消息盒子";
            return View();
        }
       
        public ActionResult judgeapply()
        {
            ViewBag.Message = "申请裁判";
            return View();
        }
        public ActionResult judgeinformation()
        {
            ViewBag.Message = "修改个人资料";
            return View();
        }
        
        public ActionResult judgetour()
        {
            ViewBag.Message = "锦标赛";
            return View();
        }
        public ActionResult judgetoursteptwo()
        {
            ViewBag.Message = "第二步";
            return View();
        }
        public ActionResult judgetourstepthree()
        {
            ViewBag.Message = "第三步";
            return View();
        }
    }
}

html/nsda/nsda/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nsda.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult index()
        {
            return View();
        }

        public ActionResult about()
        {
            ViewBag.Message = "关于";

            return View();
        }
        public ActionResult aboutp()
        {
            ViewBag.Message = "合作伙伴";
            return View();
        }
        public ActionResult aboutus()
        {
            ViewBag.Message = "联系我们";
            return View();
        }

        public ActionResult registered()
        {
            ViewBag.Message = "会员登录";
            return View();
        }
        public ActionResult forgotpwd()
        {
            ViewBag.Message = "忘记密码";

            return View();
        }
        public ActionResult forgotpwdcert()
        {
            ViewBag.Message = "忘记密码-验证码";

            return View();
        }
        public ActionResult contact()
        {
            ViewBag.Message = "联系我们";

            return View();
        }
    }
}

html/nsda/nsda/Views/Shared/_EventManage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta HTTP-EQUIV="Pragma" CONTENT="no-cache">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- uc强制竖屏 -->
    <meta name="screen-orientation" content="portrait">
    <!-- QQ强制竖屏 -->
    <meta name="x5-orientation" content="portrait">
    <!-- UC强制全屏 -->
    <meta name="full-screen" content="yes">
    <!-- QQ强制全屏 -->
    <meta name="x5-fullscreen" content="true">
    <!-- UC应用模式 -->
    <meta name="browsermode" content="application">
    <!-- QQ应用模式 -->
    <meta name="x5-page-mode" content="app">
    <!-- windows phone 点击无高光 -->
    <meta name="msapplication-tap-highlight" content="no">

    <title>@ViewBag.Title - NSDA</title>
    @Styles.Render("~/Content/asset/css/common/bootstrap.min.css")
    @Styles.Render("~/Content/asset/css/common/basic.css")
    @Styles.Render("~/Content/asset/css/common/iconfont.css?6.1.0")
    @Styles.Render("~/Content/asset/css/common/index.css?1.1.1")
    @Styles.Render("~/Content/asset/css/eventmanage/event.css?2.1.0")
    @*@Scripts.Render("~/Scripts/jquery-3.2.1.min.js")*@
    @Scripts.Render("~/Content/asset/js/jquery.min.js")
    <!--[if IE]>
    @Scripts.Render("~/Content/asset/js/jquery.min.js")
    <![endif]-->
    @Scripts.Render("~/Content/asset/js/bootstrap.min.js")
    @Scripts.Render("~/Content/asset/js/laydate/laydate.js")
</head>
<body>
    <div class="container-fluid eventtop">
        <a href="#"><i class="iconfont icon-tansuob"></i></a>
        <a href="#"><i class="iconfont icon-user"></i></a>
        <h3>NSDA 赛事管理员</h3>
        <h5>Code: 2156784</h5>
    </div>
    @*<div class="container-fluid event-nav">
        <div class="container">
            <ul>
                <a href="/Eventmanage/EventStart" class="lione"><li>发起比赛<span class="tri"></span></li></a>
                <a href="/Eventmanage/EventManage" class="litwo"><li>比赛进程管理<span class="tri"></span></li></a>
                <a href="/Eventmanage/eventmanagecenter" class="litre"><li>赛事管理员资料<span class="tri"></span></li></a>
            </ul>
        </div>
    </div>*@
    <div class="eventleft">
        <a href="/Eventmanage/eventmanage"><i class="iconfont icon-shouye"></i></a>
        <a href="/Eventmanage/EventStart"><i class="iconfont icon-add3"></i></a>
        <a href="/Eventmanage/eventmanagecenter"><i class="iconfont icon-yonghu3"></i></a>
        <a href="javascript:;"><i class="iconfont icon-youjianxinjian"></i></a>
    </div>
    <div class="body-content">
        @RenderBody()

    </div>

    <!--联系我们-->

    @Html.Partial("contact")
    <footer>
        <p>Copyright © 2005 - 2017 National Forensic League of China All Reserved</p>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>

html/nsda/nsda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta HTTP-EQUIV="Pragma" CONTENT="no-cache">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- uc强制竖屏 -->
    <meta name="screen-orientation" content="portrait">
    <!-- QQ强制竖屏 -->
    <meta name="x5-orientation" content="portrait">
    <!-- UC强制全屏 -->
    <meta name="full-screen" content="yes">
    <!-- QQ强制全屏 -->
    <meta name="x5-fullscreen" content="true">
    <!-- UC应用模式 -->
    <meta name="browsermode" content="application">
    <!-- QQ应用模式 -->
    <meta name="x5-page-mode" content="app">
    <!-- windows phone 点击无高光 -->
    <meta name="msapplication-tap-highlight" content="no">

    <title>@ViewBag.Title - NSDA</title>
    @Styles.Render("~/Content/asset/css/common/bootstrap.min.css")
    @Styles.Render("~/Content/asset/css/common/basic.css")
    @Styles.Render("~/Content/asset/css/common/iconfont.css?6.1.0")
    @Styles.Render("~/Content/asset/css/common/index.css?1.1.1")
    @*@Scripts.Render("~/Scripts/jquery-3.2.1.min.js")*@
    @Scripts.Render("~/Content/asset/js/jquery.min.js")
    <!--[if IE]>
    @Scripts.Render("~/Content/asset/js/jquery.min.js")
    <![endif]-->
    @Scripts.Render("~/Content/asset/js/parallax.min.js")
    @Scripts.Render("~/Content/asset/js/bootstrap.min.js")
    @Scripts.Render("~/Content/asset/js/laydate/laydate.js")

</head>
<body>
    <nav class="nav navbar-inverse nav-top navbar-fixed-top">
        <div class="container">
            <div class="collapse navbar-collapse">
                <div class="container search navbar-right">
                    <a href="/Player/playerregform" class="navbar-link link"> &nbsp;|&nbsp; 注册 </a><a href="/Main/registered" class="navbar-link link">登录</a>
                    <span class="iconfont icon-yonghu" aria-hidden="true"></span>
                    <a href="" id="check"><span class="iconfont icon-sousuo" aria-hidden="true"></span></a>
                    <input type="text" class="form-control" name="" placeholder="">


                </div>

            </div>
        </div>
    </nav>
    <header>
        <nav class="navbar navbar-default header container" role="navigation">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#example-navbar-collapse">

                    <span class="sr-only">切换导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:;"></a>

            </div>
            <div class="collapse navbar-collapse" id="example-navbar-collapse">
                <ul class="nav navbar-nav drop-list" id="lead">
                    <li class="">@Html.ActionLink("首页", "index", "Main")</li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            关于我们
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("关于NSDA","About","Main")</li>
                            <li><a href="javascript:;">NSDA中国</a></li>
                            <li>@Html.ActionLink("合作伙伴", "Aboutp", "Main")</li>
                            <li>@Html.ActionLink("联系我们", "Aboutus", "Main")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            会员系统 
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;">会员系统</a></li>
                            <li>@Html.ActionLink("裁判招募", "judgelogin", "Judge")</li>
                            <li>@Html.ActionLink("申请赛事管理员", "eventmanagelogin", "Eventmanage")</li>
                            <li><a href="#">排名榜单</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            赛事
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;">赛历</a></li>
                            <li><a href="javascript:;">国内赛事</a></li>
                            <li><a href="javascript:;">国际赛事</a></li>
                        </ul>
                    </li>
                    <li class=""><a href="#">课程专栏</a></li>

                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            更多
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;">辩题</a></li>
                            <li><a href="javascript:;">教材购买</a></li>
                        </ul>
                    </li>
                </ul>


                <div class="sear hidden-sm hidden-md hidden-lg">
                    <input type="text" class="form-control" name="" placeholder="">
                    <a href="" class="check2"><span class="iconfont icon-sousuo" aria-hidden="true"></span></a>
                    <span class="iconfont icon-yonghu" aria-hidden="true"></span>
                    <a href="/Home/Regform" class="navbar-link link">注册 | </a><a href="/Home/Registered" class="navbar-link link">&nbsp;登录 </a>
                </div>
            </div>
        </nav>
    </header>
   
    <div class="body-content">
        @RenderBody()
        
    </div>
    <!--联系我们-->
    <div class="container">
        <div class="row contact">
            <span></span>
            <h2>联系我们<br>GET IN TOUCH</h2>
            <p>全美演讲与辩论联盟中国办公室（NSDA China）欢迎教育、传媒、金融等社会各领域组织机构<br>与我方进行冠名、赞助等多种形式合作，共同推动学术辩论与公共演讲在中国的蓬勃发展。</p>

            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                        <img src="~/Content/asset/img/map-3.svg" alt="">
                        <p>上海市杨浦区淞沪路303号创智天地11号楼501室</p>

                    </div>
                </div>
            </div>
            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                        <img src="~/Content/asset/img/chat-user-2.svg" alt="">
                        <p>021-60452021</p>

                    </div>
                </div>
            </div>
            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                        <img src="~/Content/asset/img/mail-at.svg" alt="">
                        <p>joyofdebate@dipont-edu.com</p>

                    </div>
                </div>
            </div>

        </div>
    </div>

    @*<div class="blank">

    </div>*@
    <footer>
        <p>Copyright © 2005 - 2017 National Forensic League of China All Reserved</p>
    </footer>
  
    @RenderSection("scripts", required: false)
</body>
</html>

html/nsda/nsda/Views/Shared/_Role.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta HTTP-EQUIV="Pragma" CONTENT="no-cache">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- uc强制竖屏 -->
    <meta name="screen-orientation" content="portrait">
    <!-- QQ强制竖屏 -->
    <meta name="x5-orientation" content="portrait">
    <!-- UC强制全屏 -->
    <meta name="full-screen" content="yes">
    <!-- QQ强制全屏 -->
    <meta name="x5-fullscreen" content="true">
    <!-- UC应用模式 -->
    <meta name="browsermode" content="application">
    <!-- QQ应用模式 -->
    <meta name="x5-page-mode" content="app">
    <!-- windows phone 点击无高光 -->
    <meta name="msapplication-tap-highlight" content="no">

    <title>@ViewBag.Title - NSDA</title>
    @Styles.Render("~/Content/asset/css/bootstrap.min.css")
    @Styles.Render("~/Content/asset/css/basic.css")
    @Styles.Render("~/Content/asset/css/iconfont.css?6.1.0")
    @Styles.Render("~/Content/asset/css/index.css?1.1.1")
    @*@Scripts.Render("~/Scripts/jquery-3.2.1.min.js")*@
    @Scripts.Render("~/Content/asset/js/jquery.min.js")
    <!--[if IE]>
    @Scripts.Render("~/Content/asset/js/jquery.min.js")
    <![endif]-->
    @Scripts.Render("~/Content/asset/js/parallax.min.js")
    @Scripts.Render("~/Content/asset/js/bootstrap.min.js")
    @Scripts.Render("~/Content/asset/js/laydate/laydate.js")

</head>
<body>
    <nav class="nav navbar-inverse nav-top navbar-fixed-top">
        <div class="container">
            <div class="collapse navbar-collapse">
                <div class="container search navbar-right">
                    <a href="/Player/playerregform" class="navbar-link link"> &nbsp;|&nbsp; 注册 </a><a href="/Main/registered" class="navbar-link link">登录</a>
                    <span class="iconfont icon-yonghu" aria-hidden="true"></span>
                    <a href="" id="check"><span class="iconfont icon-sousuo" aria-hidden="true"></span></a>
                    <input type="text" class="form-control" name="" placeholder="">


                </div>

            </div>
        </div>
    </nav>
    <header>
        <nav class="navbar navbar-default header container" role="navigation">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#example-navbar-collapse">

                    <span class="sr-only">切换导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:;"></a>

            </div>
            <div class="collapse navbar-collapse" id="example-navbar-collapse">
                <ul class="nav navbar-nav drop-list" id="lead">
                    <li class="">@Html.ActionLink("首页", "index", "Main")</li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            关于我们
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("关于NSDA", "About", "Main")</li>
                            <li><a href="javascript:;">NSDA中国</a></li>
                            <li>@Html.ActionLink("合作伙伴", "Aboutp", "Main")</li>
                            <li>@Html.ActionLink("联系我们", "Aboutus", "Main")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            会员系统
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;">会员系统</a></li>
                            <li>@Html.ActionLink("裁判招募", "judgelogin", "Judge")</li>
                            <li>@Html.ActionLink("申请赛事管理员", "eventmanagelogin", "Eventmanage")</li>
                            <li><a href="#">排名榜单</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            赛事
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;">赛历</a></li>
                            <li><a href="javascript:;">国内赛事</a></li>
                            <li><a href="javascript:;">国际赛事</a></li>
                        </ul>
                    </li>
                    <li class=""><a href="#">课程专栏</a></li>

                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            更多
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;">辩题</a></li>
                            <li><a href="javascript:;">教材购买</a></li>
                        </ul>
                    </li>
                </ul>


                <div class="sear hidden-sm hidden-md hidden-lg">
                    <input type="text" class="form-control" name="" placeholder="">
                    <a href="" class="check2"><span class="iconfont icon-sousuo" aria-hidden="true"></span></a>
                    <span class="iconfont icon-yonghu" aria-hidden="true"></span>
                    <a href="/Home/Regform" class="navbar-link link">注册 | </a><a href="/Home/Registered" class="navbar-link link">&nbsp;登录 </a>
                </div>
            </div>
        </nav>
    </header>

    <div class="body-content">
        @RenderBody()

    </div>
    <!--联系我们-->

    @*<div class="blank">

        </div>*@
    <footer>
        <p>Copyright © 2005 - 2017 National Forensic League of China All Reserved</p>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>

html/nsda/nsda/Views/Shared/contact.cshtml
<link href="~/Content/asset/css/index.css?1.1.0" rel="stylesheet" />

<div class="container">
    <div class="row contact">
        <span></span>
        <h2>联系我们<br>GET IN TOUCH</h2>
        <p>全美演讲与辩论联盟中国办公室（NSDA China）欢迎教育、传媒、金融等社会各领域组织机构<br>与我方进行冠名、赞助等多种形式合作，共同推动学术辩论与公共演讲在中国的蓬勃发展。</p>

        <div class="col-sm-4 col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <img src="~/Content/asset/img/map-3.svg" alt="">
                    <p>上海市杨浦区淞沪路303号创智天地11号楼501室</p>

                </div>
            </div>
        </div>
        <div class="col-sm-4 col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <img src="~/Content/asset/img/chat-user-2.svg" alt="">
                    <p>021-60452021</p>

                </div>
            </div>
        </div>
        <div class="col-sm-4 col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <img src="~/Content/asset/img/mail-at.svg" alt="">
                    <p>joyofdebate@dipont-edu.com</p>

                </div>
            </div>
        </div>

    </div>
</div>